### ISSUE TITLE
createSlot is not assignable

### ISSUE THREAD

**Issue by sergio222-dev** [kirillvy/react-slots#10]
the problem line:
```
export const Drawer = createSlot<DrawerContainerProps>(DrawerContainer);
```

my component and interface:

```
export const DrawerContainer: React.FunctionComponent<DrawerContainerProps> = ({ isShowing, children }) => {
  const styles = useStyles({ isShowing });
  return <div className={styles.root}>{children}</div>;
};
```
```
export interface DrawerContainerProps {
  isShowing: boolean;
}
```

the error:

> Error:(6, 56) TS2345: Argument of type 'FunctionComponent<DrawerContainerProps>' is not assignable to parameter of type 'ComponentClass<{}, any> | FunctionComponent<{}> | undefined'.
  Type 'FunctionComponent<DrawerContainerProps>' is not assignable to type 'FunctionComponent<{}>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type '{ children?: ReactNode; }' is not assignable to type 'PropsWithChildren<DrawerContainerProps>'.
        Property 'isShowing' is missing in type '{ children?: ReactNode; }' but required in type 'DrawerContainerProps'.

what is what i'm doing wrong?

**Comment by kirillvy** [comment]
Hi, Sergio, thank you for your feedback. I have not been able to replicate the problem, at least on the current environment (0.4.1). Could you please tell me the version you are using, so that I can investigate the problem?

**Comment by sergio222-dev** [comment]
I make a repository where the error is replicated, [here](https://github.com/sergio222-dev/slotcomponent-typescript-error).
I'm using the 0.4.1 version

**Comment by kirillvy** [comment]
Thank you, fixed typing issue. Please see `slottr@0.4.3`
